### ISSUE TITLE
Account's Contact Infos

### ISSUE THREAD

**Issue by oguzhankarabulut** [linkfy/Tools-for-Instagram#13]
Hey, firstly your tool is amazing thanks for work and share! I want to ask a question about get user info script. In this case i thanks with these script we can see in output if user is business and added to him/her email or phone number.  We can see in output biography, follower count, following count, external url etc. but we can not see contact informations like email or phone number. Is there anyway to see them? I mean these infos not logged account infos, other users infos.
Thank again!

**Comment by linkfy** [comment]
Hey! If the user is public, it must be available by simply using the getUserInfo function:

```javascript
require('./src/tools-for-instagram');

(async () => {
    let ig = await login();
    console.log(await getUserInfo(ig, "exampleAccount"));
    
})();

```

you will get:

`
....
public_email: 'XXXXX@XXXX.com',
public_phone_country_code: 'XX',
public_phone_number: 'XXXXXXXXX',
....
`

**Comment by oguzhankarabulut** [comment]
Thx for reply! I will try and share result with you
