### ISSUE TITLE
Share to other apps?

### ISSUE THREAD

**Issue by WhyToFly** [linkfy/Tools-for-Instagram#14]
Hey, thank you so much for this tool, it is exactly what I was looking for!
Right now I am manually sharing my posts from Instagram to Facebook (can be done through the Instagram app by going to a post->...->Post to other Apps...->Facebook). Is there a way to do this through this tool?

**Comment by linkfy** [comment]
Hey! Is not yet implemented but you can export the data and call the Facebook Api to do the same action as a quick way to get some results.

**Comment by WhyToFly** [comment]
> Hey! Is not yet implemented but you can export the data and call the Facebook Api to do the same action as a quick way to get some results.

Ok I will check that out, thank you for the quick reply!
