### ISSUE TITLE
TypeError: Cannot read property 'green' of undefined

### ISSUE THREAD

**Issue by Abdulsamipy** [linkfy/Tools-for-Instagram#21]
Hi, so when im trying to run the default example.js file  I'm getting the following error 

`Not using proxy
Mobile/Residential proxy recommended
(node:1404) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'green' of undefined`

**Comment by linkfy** [comment]
Can you execute another time the script? Sometimes posts are deleted a second after it is posted, at which line are you getting the error? Which was the last action done?

**Comment by Abdulsamipy** [comment]
so i did try to run another type of script like_follow.js  I'm getting the following message 

`Not using proxy
Mobile/Residential proxy recommended
(node:8900) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'green' of undefined
    at login (C:\Users\Desktop\Tools-for-Instagram-master\src\login.js:150:74)
    at C:\Users\Desktop\Tools-for-Instagram-master\bots\like_and_follow.js:39:20
    at Object.<anonymous> (C:\Users\Desktop\Tools-for-Instagram-master\bots\like_and_follow.js:66:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
(node:8900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Nerixyz** [comment]
You haven't set `IG_USERNAME` (and maybe also `IG_PASSWORD`)

**Comment by Jork555** [comment]
Hi, I am having the same problem like Abdulsamipy  
Not using proxy Mobile/Residential proxy recommended (node:1404) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'green' of undefined
I did  setup  IG_USERNAME  IG_PASSWORD)

**Comment by Nerixyz** [comment]
> I did setup IG_USERNAME IG_PASSWORD)

You probably did it wrong. How did you do it?

**Comment by Jork555** [comment]
HI,  in this file   .env_example    i changed it to       something.env
I changed first two lines inside  to :
IG_USERNAME=john
IG_PASSWORD=Newyork123
my username is john password  Newyork123
  .env_example  is file in main root

**Comment by Nerixyz** [comment]
### 1. Change your password

and...
You have to rename it to `.env` that's why it has  the "extension" `_example`

**Comment by Jork555** [comment]
I renamed  it to example.env  is that Ok ? But faiiled with that also .
Or you mean it needs to be      _example.env      ?

**Comment by virginsince1997** [comment]
Just rename it to .env make sure it's in the root of the folder and your
script is also in the root of the folder

**Comment by Jork555** [comment]
Sorry I am confused, maybe stupid question but windows doesn't allow to rename it without name just .env

**Comment by virginsince1997** [comment]
Download notepad ++, close all folders and try renaming it with notepad++

**Comment by Jork555** [comment]
TNX that was it , did try earlier just .env but gave up bcs of WIndows
Could you direct me with this maybe , trying to make some first steps
Trying to log with marija.maki82
No cookie file found in loadCookies function
(node:4888) UnhandledPromiseRejectionWarning: RequestError: Error: tunneling socket could not be established, statusCode=400
    at Request.faultTolerantRequest (C:\Users\Administrator\Tools-for-Instagram\node_modules\instagram-private-api\dist\core\request.js:131:19)
(node:4888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4888) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by virginsince1997** [comment]
This is a proxy issue or your connection, make sure IG_PROXY = in .env is
empty

**Comment by linkfy** [comment]
Thanks for the help boys, is it solved?
