### ISSUE TITLE
Is there post image tool

### ISSUE THREAD

**Issue by Jork555** [linkfy/Tools-for-Instagram#22]
Is there maybe any ready to go  script for testing upload image/post image on IG
Hope this is the right place to ask, apologize if not...

**Comment by virginsince1997** [comment]
Check the documentation and examples folder

**Comment by Jork555** [comment]
HI, tnx for helping, i did go through everything, can you maybe direct me a little bit more 
I don't have examples folder ( you mean folder BOTS where examples templates are)
I managed to find like and follow templates there , 
Maybe the right question is do i need to write  post image script or is there already some template I can try

**Comment by linkfy** [comment]
> HI, tnx for helping, i did go through everything, can you maybe direct me a little bit more
> I don't have examples folder ( you mean folder BOTS where examples templates are)
> I managed to find like and follow templates there ,
> Maybe the right question is do i need to write post image script or is there already some template I can try


Hey, take a look at  readme on section 'uploadPicture'
