### ISSUE TITLE
likeRecentHashtagsByIntervals error

### ISSUE THREAD

**Issue by cheezeburger** [linkfy/Tools-for-Instagram#26]
I'm getting this error using likeRecentHashtagsByIntervals error. Below is all my codes. Nothing fancy, just settings and calling the function.

`let ig = await login();
let likesPerInterval = 24;
let waitMinutesBetweenLikes = 60;`

  `let intervals = [ ["0:00",    "23:00"] ];
  let hashtagArray = [
		 "meme",
		 "memes",
		 "dailymeme",
		 "dailymemes"
  ];`

 `let likeInterval = likeRecentHashtagsByIntervals(
                                                    ig,
                                                    hashtagArray, 
                                                    intervals, 
                                                    likesPerInterval,
                                                    waitMinutesBetweenLikes);`

![image](https://user-images.githubusercontent.com/10891873/82294997-971a5c80-99e1-11ea-9b16-1f2d7a76f6f0.png)

Anyone knows what's wrong?

**Comment by linkfy** [comment]
can you try to put try{}catch() on the piece of code failing? maybe the connection is unstable sometimes

**Comment by maxiperpen** [comment]
i have the same problem =(

**Comment by Nerixyz** [comment]
@maxiperpen Try to enable the debug-log by setting the environment variable `DEBUG` to `ig:*`. Also make sure you have the latest version.

**Comment by cheezeburger** [comment]
> can you try to put try{ }catch(e){ } on the piece of code failing? maybe the connection is unstable sometimes

The catch block was not able to catch the error

**Comment by Nerixyz** [comment]
> The catch block was not able to catch the error

Does your entire process crash or does it continue?

**Comment by cheezeburger** [comment]
> > The catch block was not able to catch the error
> 
> Does your entire process crash or does it continue?

It terminates the entire process. I tried catching the entire main function and the function itself but no luck.

**Comment by virginsince1997** [comment]
Mqtt error can't be caught, I also have the issue, @Linkfy says he's
working on it

**Comment by Nerixyz** [comment]
Try to reinstall the library. (Delete `node_modules` and run `npm i`)

**Comment by virginsince1997** [comment]
Did that yesterday.. Did you just fix it?

**Comment by virginsince1997** [comment]
![Screenshot_20200529-152047](https://user-images.githubusercontent.com/21218962/83349327-fe160a80-a32b-11ea-98a3-df4502e8f9fe.png)

**Comment by Nerixyz** [comment]
You need to import `imstagram_mqtt` from npm instead of github. Npm ignores the `src/` directory, so the library doesn't compile. This has to be done in the `package.json` (replace `"instagram_mqtt": "..."` with `"instagram_mqtt": "^0.2.16"` (cc @linkfy )

**Comment by virginsince1997** [comment]
> You need to import `imstagram_mqtt` from npm instead of github. Npm ignores the `src/` directory, so the library doesn't compile. This has to be done in the `package.json` (replace `"instagram_mqtt": "..."` with `"instagram_mqtt": "^0.2.16"` (cc @linkfy )

It's working, thank you 😀👍

**Comment by virginsince1997** [comment]
Although mqtt still throws an error, ive never seen this one
![Screenshot_20200531-112514~2](https://user-images.githubusercontent.com/21218962/83350112-b4c8b980-a331-11ea-9199-1761f071402a.png)

**Comment by Nerixyz** [comment]
This shouldn't end the entire process as it's an event. The line responsible may be https://github.com/linkfy/Tools-for-Instagram/blob/master/src/login.js#L217 as instagram sends a config update. The App also doesn't subscribe to it anymore.

**Comment by virginsince1997** [comment]
> This shouldn't end the entire process as it's an event. The line responsible may be https://github.com/linkfy/Tools-for-Instagram/blob/master/src/login.js#L217 as instagram sends a config update. The App also doesn't subscribe to it anymore.

Thanks for your response

**Comment by linkfy** [comment]
Thanks for the feedback! I will try to comment that line for a few days and see if the problem persist. What is the functionality of ClientConfigUpdate subscription in the App?

**Comment by Nerixyz** [comment]
> What is the functionality of ClientConfigUpdate subscription in the App?

It's probably th same as `qe` or `qp` which is already done over HTTP.

**Comment by linkfy** [comment]
> > What is the functionality of ClientConfigUpdate subscription in the App?
> 
> It's probably th same as `qe` or `qp` which is already done over HTTP.

Ah I see, thank you!
