### ISSUE TITLE
Unhandled Promise Rejection Warning on request.js

### ISSUE THREAD

**Issue by ogcyborg** [linkfy/Tools-for-Instagram#35]
Hi,

Occasionally I receive UnhandledPromiseRejectionWarning from request.js.  I suspect this happens when IG doesn't like something with the account.  My question is how can I trap this error so my script can quit instead of getting the UnhandledPromiseRejectionWarning.  I've tried to catch it a variety of ways but so far have not been able to.

(node:8768) UnhandledPromiseRejectionWarning: IgResponseError: POST /api/v1/accounts/contact_point_prefill/ - 429 -; Please wait a few minutes before you try again.
    at Request.handleResponseError (/home/ubuntu/Tools-for-Instagram/node_modules/instagram-private-api/dist/core/request.js:125:16)
    at Request.send (/home/ubuntu/Tools-for-Instagram/node_modules/instagram-private-api/dist/core/request.js:53:28)
    at <anonymous>
(node:8768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8768) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by linkfy** [comment]
Hey! Take a look on this line, maybe it will help you:
https://github.com/linkfy/Tools-for-Instagram/blob/e86d150ac3ecf5608a0d139d15d162e7063e908d/benckmarkResearch.js#L85

**Comment by ogcyborg** [comment]
Looking into it now, thank you so much

**Comment by ogcyborg** [comment]
Problem solved, thank you
