### ISSUE TITLE
I wanted it ready app for Windows 10

### ISSUE THREAD

**Issue by pcexpertq8** [linkfy/Tools-for-Instagram#41]
Dear guys,

Honestly, I liked this work you have did but I am not pretty understanding these coding or how to use it. I would like to have it ready app to use it on Windows 10, please. I couldn't find any explanation video anywhere.

If anyone can help, kindly let me know and the cost please?

I wanted an app to have all these functionalities listed in these subject.
Kind regards,

**Comment by EsteveSegura** [comment]
**Good afternoon,**

The code is written in the most understandable way for the general public and in the case of not understanding the code at all, there is documentation and example cases that are very enlightening.

What other help do you think would be useful?

**Cheers,**
