### ISSUE TITLE
cannot login 

### ISSUE THREAD

**Issue by harrykwan** [linkfy/Tools-for-Instagram#48]
| IgResponseError: POST /api/v1/accounts/get_prefill_candidates/ - 302 Found; i
0|index  |     at Request.handleResponseError (/home/bitnami/venbotv3/server/node_moduless
/instagram-private-api/dist/core/request.js:125:16)f
0|index  |     at Request.send (/home/bitnami/venbotv3/server/node_modules/instagram-priv:
ate-api/dist/core/request.js:53:28)0
0|index  |     at async AccountRepository.getPrefillCandidates (/home/bitnami/venbotv3/ses 
rver/node_modules/instagram-private-api/dist/repositories/account.repository.js:273:26)"

**Comment by echoedexistence** [comment]
having this same issue as well

**Comment by Oyetomi** [comment]
npm update . Worked

**Comment by WhyToFly** [comment]
I also can't log in, but with a different error:

```
node:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);
          ^

IgResponseError: POST /api/v1/accounts/contact_point_prefill/ - 429 -; Please wait a few minutes before you try again.
    at Request.handleResponseError (/Users/christopherh/Desktop/insta/tfi/Tools-for-Instagram/node_modules/instagram-private-api/dist/core/request.js:125:16)
    at Request.send (/Users/christopherh/Desktop/insta/tfi/Tools-for-Instagram/node_modules/instagram-private-api/dist/core/request.js:53:28)
    at async AccountRepository.contactPointPrefill (/Users/christopherh/Desktop/insta/tfi/Tools-for-Instagram/node_modules/instagram-private-api/dist/repositories/account.repository.js:262:26)
```

I already updated to the newest version.

**Comment by Oyetomi** [comment]
Too many requests. I get this too, almost after some minutes.

**Comment by WhyToFly** [comment]
Yup, seems to be working now. I thought something broke because it has been running fine for months but suddenly didn’t work at all anymore yesterday. Thanks!

**Comment by WhyToFly** [comment]
Alright, it worked for one post. I am getting the same error even with an account that has not been used with a bot before so I can't possibly have exceeded any rate limits :/

**Comment by harrykwan** [comment]
i still got error running on aws
but its ok for local device

IgResponseError: POST /api/v1/accounts/contact_point_prefill/ - 429 -; Please w
ait a few minutes before you try again.
0|index  |     at Request.handleResponseError (/home/bitnami/venbotv3/server/node_modules/
instagram-private-api/dist/core/request.js:125:16)
0|index  |     at Request.send (/home/bitnami/venbotv3/server/node_modules/instagram-priva
te-api/dist/core/request.js:53:28)
0|index  |     at async AccountRepository.contactPointPrefill (/home/bitnami/venbotv3/serv
er/node_modules/instagram-private-api/dist/repositories/account.repository.js:262:26)

**Comment by harrykwan** [comment]
should be related?
https://github.com/dilame/instagram-private-api/issues/1324

**Comment by linkfy** [comment]
yep! an npm update will clear the problem
